# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-23 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informationpage', '0004_restaraunt_information_shoppingmall_information'),
    ]

    operations = [
        migrations.CreateModel(
            name='museum_page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('descrption', models.CharField(max_length=256)),
                ('phonenumber', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('imagelink', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='restaraunt_page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('descrption', models.CharField(max_length=256)),
                ('phonenumber', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('imagelink', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='shoppingmall_page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('descrption', models.CharField(max_length=256)),
                ('phonenumber', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('imagelink', models.CharField(max_length=30)),
            ],
        ),
        migrations.RenameModel(
            old_name='museum_information',
            new_name='hotel_page',
        ),
        migrations.DeleteModel(
            name='hotel_information',
        ),
        migrations.DeleteModel(
            name='restaraunt_information',
        ),
        migrations.DeleteModel(
            name='shoppingmall_information',
        ),
    ]
