# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-23 12:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('informationpage', '0005_auto_20171023_2226'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='shoppingmall_page',
            new_name='hotels',
        ),
        migrations.RenameModel(
            old_name='restaraunt_page',
            new_name='museums',
        ),
        migrations.RenameModel(
            old_name='museum_page',
            new_name='restaraunts',
        ),
        migrations.RenameModel(
            old_name='hotel_page',
            new_name='shoppingmalls',
        ),
    ]
