# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-24 04:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informationpage', '0007_auto_20171023_2232'),
    ]

    operations = [
        migrations.CreateModel(
            name='city_park',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('descrption', models.CharField(max_length=256)),
                ('phonenumber', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('imagelink', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='college',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('descrption', models.CharField(max_length=256)),
                ('phonenumber', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('imagelink', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='industrie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('descrption', models.CharField(max_length=256)),
                ('phonenumber', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('imagelink', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='zoo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('descrption', models.CharField(max_length=256)),
                ('phonenumber', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('imagelink', models.CharField(max_length=30)),
            ],
        ),
    ]
