# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-24 07:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informationpage', '0008_city_park_college_industrie_zoo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city_park',
            name='imagelink',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='college',
            name='imagelink',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='imagelink',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='industrie',
            name='imagelink',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='museum',
            name='imagelink',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='restaraunt',
            name='imagelink',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='shoppingmall',
            name='imagelink',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='zoo',
            name='imagelink',
            field=models.CharField(max_length=100),
        ),
    ]
