# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-25 12:44
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informationpage', '0011_auto_20171025_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='imagelink',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='/SmartCityProject/storage'), upload_to=''),
        ),
    ]
