# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-25 13:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('informationpage', '0012_auto_20171025_2244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city_park',
            name='imagelink',
        ),
        migrations.RemoveField(
            model_name='college',
            name='imagelink',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='imagelink',
        ),
        migrations.RemoveField(
            model_name='industrie',
            name='imagelink',
        ),
        migrations.RemoveField(
            model_name='museum',
            name='imagelink',
        ),
        migrations.RemoveField(
            model_name='restaraunt',
            name='imagelink',
        ),
        migrations.RemoveField(
            model_name='shoppingmall',
            name='imagelink',
        ),
        migrations.RemoveField(
            model_name='zoo',
            name='imagelink',
        ),
    ]
