# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-25 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informationpage', '0013_auto_20171025_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city_park',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='college',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='industrie',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='museum',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='restaraunt',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='shoppingmall',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='zoo',
            name='address',
            field=models.CharField(max_length=100),
        ),
    ]
