# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-25 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informationpage', '0015_auto_20171025_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
