# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-26 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informationpage', '0026_auto_20171026_0149'),
    ]

    operations = [
        migrations.CreateModel(
            name='citymap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('citymap', models.ImageField(blank=True, null=True, upload_to='storage/citymap')),
            ],
        ),
    ]
