# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-28 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informationpage', '0027_citymap'),
    ]

    operations = [
        migrations.AddField(
            model_name='city_park',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='storage'),
        ),
        migrations.AddField(
            model_name='college',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='storage'),
        ),
        migrations.AddField(
            model_name='industrie',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='storage'),
        ),
        migrations.AddField(
            model_name='museum',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='storage'),
        ),
        migrations.AddField(
            model_name='restaraunt',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='storage'),
        ),
        migrations.AddField(
            model_name='shoppingmall',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='storage'),
        ),
        migrations.AddField(
            model_name='zoo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='storage'),
        ),
    ]
