# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-28 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informationpage', '0028_auto_20171028_2338'),
    ]

    operations = [
        migrations.CreateModel(
            name='libary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('descrption', models.CharField(max_length=256)),
                ('phonenumber', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='storage')),
            ],
        ),
    ]
