# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-29 09:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('informationpage', '0030_auto_20171029_0340'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='restaraunt',
            new_name='restaurant',
        ),
        migrations.RenameField(
            model_name='city_park',
            old_name='descrption',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='college',
            old_name='descrption',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='descrption',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='industrie',
            old_name='descrption',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='libary',
            old_name='descrption',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='museum',
            old_name='descrption',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='descrption',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='shoppingmall',
            old_name='descrption',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='zoo',
            old_name='descrption',
            new_name='description',
        ),
    ]
