# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-29 09:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('informationpage', '0031_auto_20171029_1940'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='libary',
            new_name='library',
        ),
    ]
